stages:
  collect_data:
    cmd: python src/data/gather_data.py
    deps:
      - src/data/gather_data.py
    outs:
      - data/raw_data.csv

  preprocess_data:
    cmd: python src/preprocessing/preprocess_data.py
    deps:
      - src/preprocessing/preprocess_data.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed_data.csv
    outs:
      - models/model.pkl
      - mlruns